### ISSUE TITLE
bind9: unrecognized service

### ISSUE THREAD

**Issue by sirphoenix** [bloodhunterd/Froxlor#6]
When trying to run this using your example docker-compose.yml i get the following error:

```
Starting froxlor-docker_froxlor_1 ... done
Attaching to froxlor-docker_froxlor_1
froxlor_1  | Starting periodic command scheduler: cron.
froxlor_1  | bind9: unrecognized service
```

nothing happens after this and nothing is listening on either port 80 or 443.

docker-compose.yml for reference:
```
version: '3'

services:
  froxlor:
    image: bloodhunterd/froxlor
    ports:
      - '80'
      - '443'
    restart: unless-stopped
    volumes:
      - ./froxlor/:/var/www/froxlor/
      - ./customers/logs/:/var/customers/logs/
      - ./customers/mail/:/var/customers/mail/
      - ./customers/webs:/var/customers/webs/
      - ./.acme.sh/:/root/.acme.sh/
      - ./ssl/:/etc/ssl/froxlor/

```
